---

- name: clean up components and update files
  ansible.windows.win_shell: Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase
  when: "'Windows Server 2008' not in ansible_distribution"
  failed_when: false

- name: clean up system
  ansible.builtin.include_tasks: clean_up_with_cleanmgr.yml
  when: "'Windows Server 2008' in ansible_distribution"

- name: clean up components and update files
  ansible.windows.win_shell: Dism.exe /online /Cleanup-Image /SpSuperseded
  when: "'Windows Server 2008' in ansible_distribution"
  failed_when: false
