---

- name: install cloudbase init package
  ansible.windows.win_package:
    path: '{{ cloudbase_init_download_url }}'
    product_id: '{ED85F19F-057A-4EE6-BC8D-F576DEACE78D}'
    arguments:
      - /qn
    state: present
  register: install_cloudbase_init
  until: install_cloudbase_init is success
  delay: 3
  retries: 5

- name: ensure cloudbase-init service is disabled
  ansible.windows.win_service:
    name: cloudbase-init
    start_mode: disabled
