---

- name: run scheduled task
  raw: 'SCHTASKS /Run /TN upgrade'
  args:
    executable: cmd.exe
  changed_when: False
  check_mode: no

- pause:
    seconds: "{{ upgrade_wait_timeout }}"

- name: wait for powershell upgrade task to finish
  raw: '((schtasks /query /TN upgrade)[4] -split " +")[-2]'
  changed_when: False
  check_mode: no
  register: upgrade_status_check
  failed_when: false
  until: (upgrade_status_check.stdout | trim | lower) == 'ready'
  delay: 10
  retries: 10

- name: check powershell version
  raw: Write-Host "$($psversiontable.psversion.major).$($psversiontable.psversion.minor)"
  changed_when: False
  check_mode: no
  ignore_errors: yes
  register: powershell_current_version

- name: set installed powershell version
  set_fact:
    powershell_installed_version: "{{ powershell_current_version.stdout | trim }}"

- name: debug powershell installed version
  debug:
    msg: "installed powershell version: {{ powershell_installed_version }}"