---

- include_tasks: enable_powershell.yml

# enable tls system_default
# on Windows 7 SP1, TLS 1.1 and 1.2 is not enabled by default
# this hotfix is needed to fix that
# see https://support.microsoft.com/en-us/topic/support-for-tls-system-default-versions-included-in-the-net-framework-3-5-1-on-windows-7-sp1-and-server-2008-r2-sp1-5ef38dda-8e6c-65dc-c395-62d2df58715a
- name: enable tls system_default
  include_tasks: raw_hotfix_apply.yml
  vars:
    hotfix_download_url: "{{ enable_tls_support_hotfix.url }}"
    hotfix_download_location: "{{ enable_tls_support_hotfix_download_location }}"
    hotfix_file: "{{ enable_tls_support_hotfix.file }}"
    hotfix_pause_seconds: 60

- name: start windows update service
  raw: net start wuauserv
  args:
    executable: cmd.exe
  failed_when: false

- name: check powershell version (1/2)
  raw: Write-Host "$($psversiontable.psversion.major).$($psversiontable.psversion.minor)"
  changed_when: False
  check_mode: no
  ignore_errors: yes
  register: powershell_current_version

- name: set installed powershell version (1/2)
  set_fact:
    powershell_installed_version: "{{ powershell_current_version.stdout | trim }}"

- name: debug powershell installed version (1/2)
  debug:
    msg: "installed powershell version: {{ powershell_installed_version }}"

- name: debug powershell target version
  debug:
    msg: "target powershell version: {{ powershell_target_version }}"

- name: check to see if .NET needs to be installed
  raw: |
    # detect if .NET 4.5.2 is not installed
    $dotnet_path = "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full"
    $dotnet_upgrade_needed = $false
    if (-not (Test-Path -Path $dotnet_path)) {
        $dotnet_upgrade_needed = $true
    } else {
        $dotnet_version = Get-ItemProperty -Path $dotnet_path -Name Release -ErrorAction SilentlyContinue
        if ($dotnet_version) {
            # 379893 == 4.5.2
            if ($dotnet_version.Release -lt 379893) {
                $dotnet_upgrade_needed = $true
            }
        } else {
            $dotnet_upgrade_needed = $true
        }
    }
    return $dotnet_upgrade_needed
  changed_when: False
  check_mode: no
  ignore_errors: yes
  register: dot_net_required

- name: ensure no wusa service is running for hotfix installation
  raw: get-process wusa -ErrorAction SilentlyContinue
  changed_when: False
  check_mode: no
  register: check_wusa_process
  failed_when: false
  until: check_wusa_process.rc != 0
  delay: 60
  retries: 10

- name: install .NET 4.5.2
  include_tasks: dot_net_452_install.yml
  when: ("True" in (dot_net_required.stdout | trim))  # bool doesn't work here because powershell 2.0 returns messy output

# install windows management framework 3.0 (upgrade to powershell 3.0)
- name: install windows management framework 3.0 (upgrade to powershell 3.0)
  include_tasks: raw_hotfix_apply.yml
  vars:
    hotfix_download_url: "{{ wmf_3_hotfix.url }}"
    hotfix_download_location: "{{ wmf_3_hotfix_download_location }}"
    hotfix_file: "{{ wmf_3_hotfix.file }}"
    hotfix_pause_seconds: 240
  when: (powershell_installed_version|int) is version(powershell_target_version|int, '<')

- name: check powershell version (2/2)
  raw: Write-Host "$($psversiontable.psversion.major).$($psversiontable.psversion.minor)"
  changed_when: False
  check_mode: no
  ignore_errors: yes
  register: powershell_current_version

- name: set installed powershell version (2/2)
  set_fact:
    powershell_installed_version: "{{ powershell_current_version.stdout | trim }}"

- name: debug powershell installed version (2/2)
  debug:
    msg: "installed powershell version: {{ powershell_installed_version }}"

# apply winrm memory hotfix for powershell 3.0
- name: apply winrm memory hotfix for powershell 3.0
  include_tasks: winrm-memfix.yml
  when: powershell_installed_version|int is version(3, '==')

- name: ensure auto login is disabled
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 0
    type: string

- name: ensure auto login creds are removed
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "{{ item }}"
    state: absent
  loop:
    - DefaultUserName
    - DefaultPassword