---

- name: kill onedrive process
  ansible.windows.win_shell: Stop-Process -Name OneDrive
  failed_when: false

- name: uninstall onedrive
  ansible.windows.win_shell: '{{ ansible_env.SystemRoot }}\SysWOW64\OneDriveSetup.exe /uninstall'
  failed_when: false

- name: remove onedrivesync package
  ansible.windows.win_shell: get-appxpackage *Microsoft.OneDriveSync* | remove-appxpackage -AllUsers
  failed_when: false

- name: remove onedrive directories
  ansible.windows.win_file:
    path: '{{ item }}'
    state: absent
  failed_when: false
  loop:
    - '{{ ansible_env.USERPROFILE }}\OneDrive'
    - '{{ ansible_env.LOCALAPPDATA }}\Microsoft\OneDrive'
    - '{{ ansible_env.ProgramData }}\Microsoft OneDrive'
    - C:\OneDriveTemp

- name: delete registry keys
  ansible.windows.win_regedit:
    path: '{{ item }}'
    state: absent
    delete_key: true
  loop:
    - HKCR:\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}
    - HKCR:\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}
