---
# this update is needed to support ssl support on Windows Server 2008 R2

- name: download hotfix
  win_get_url:
    url: '{{ ssl_security_update_hotfix.url }}'
    dest: '{{ ssl_security_update_hotfix_download_location }}\{{ ssl_security_update_hotfix.file }}'
  register: download_hotfix
  until: download_hotfix is success
  delay: 3
  retries: 5

- block:
    - include_tasks: hotfix_ps4.yml
  rescue:
    - include_tasks: hotfix_ps3.yml
  when: ansible_powershell_version is version('4', '>=')
  vars:
    hotfix_download: "{{ ssl_security_update_hotfix }}"
    hotfix_temp_directory: "{{ ssl_security_update_hotfix_download_location }}"

- include_tasks: hotfix_ps3.yml
  when: ansible_powershell_version is version('3', '==')
  vars:
    hotfix_download: "{{ ssl_security_update_hotfix }}"
    hotfix_temp_directory: "{{ ssl_security_update_hotfix_download_location }}"

- name: ensure hotfix file is removed
  win_file:
    path: '{{ ssl_security_update_hotfix_download_location }}\{{ ssl_security_update_hotfix.file }}'
    state: absent

- name: reboot if needed
  win_reboot:
  when: hotfix_install.reboot_required | default(True)