---

- name: get Windows ADK uninstall command
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{d794748d-72e9-45d7-9ab7-83d6c4c80f7f}
    name: QuietUninstallString
  register: windows_adk_uninstall_string

- name: uninstall Windows ADK
  ansible.windows.win_shell: "{{ windows_adk_uninstall_string.value }}"
  args:
    executable: cmd
  when: windows_adk_uninstall_string.value is defined

- name: ensure Windows ADK with DISM is removed
  chocolatey.chocolatey.win_chocolatey:
    name: windows-adk-deploy
    state: absent
  register: remove_win_adk_dism
  until: remove_win_adk_dism is success
  delay: 3
  retries: 5
